name:                lambdas
version:             0.1.0.0
github:              "jpyamamoto/lambdas"
license:             MIT
author:              "Juan Pablo Yamamoto"
maintainer:          "jpyamamoto@ciencias.unam.mx"
copyright:           "2023 Juan Pablo Yamamoto"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Interpreters for several versions of Lambda calculi with different characteristics.
# category:            Compilers/Interpreters

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Interpreters for several versions of Lambda calculi with different characteristics.

dependencies:
- base >= 4.7 && < 5
- megaparsec >= 9.2
- text >= 1.0
- mtl >= 2.2
- parser-combinators >= 1.3
- containers >= 0.6

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-do-bind

library:
  source-dirs: src
  default-extensions:
    - OverloadedStrings

executables:
  untyped:
    main:                Main.hs
    source-dirs:         app/Untyped
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambdas
  typed:
    main:                Main.hs
    source-dirs:         app/Typed
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambdas
  systemf:
    main:                Main.hs
    source-dirs:         app/SystemF
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambdas

tests:
  lambdas-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambdas
